name: Release on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get previous tag
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --max-count=1))
          echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_ENV

      - name: Increment version number
        run: |
          echo "Previous release tag: $PREVIOUS_TAG"
          IFS='.' read -r -a version <<< "$RELEASE_VERSION"
          version[2]=$((version[2]+1))
          echo "New release tag: v${version[0]}.${version[1]}.${version[2]}"
          echo "NEW_TAG=v${version[0]}.${version[1]}.${version[2]}" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: Release ${{ env.NEW_TAG }}
          body: ${{ github.event.pull_request.body }}

      - name: Comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          comment_url="${{ github.event.pull_request.comments_url }}"
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/json" --data "{ \"body\": \"Release created: https://github.com/${{ github.repository }}/releases/tag/${{ env.NEW_TAG }}\" }" "$comment_url"